# Generated by Django 3.2.8 on 2022-07-14 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(default=None, max_length=255, null=True)),
                ('imageUrl', models.CharField(default=None, max_length=255, null=True)),
                ('notificationFor', models.IntegerField(choices=[(1, 'admin'), (2, 'patient'), (3, 'provider')], default=1)),
                ('notificationType', models.IntegerField(choices=[(1, 'pushNotificaion'), (2, 'callNotification')], default=1)),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userId_Notofications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
