# Generated by Django 3.2.8 on 2022-07-26 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerRating', models.IntegerField(blank=True, null=True)),
                ('feedbackComment', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('providerId', models.ForeignKey(db_column='providerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_to_providerId', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='rating_from_userId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_review_providers',
            },
        ),
        migrations.CreateModel(
            name='FavouriteProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('providerId', models.ForeignKey(db_column='providerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_to_providerId', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_from_userId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite_providers',
            },
        ),
    ]
