# Generated by Django 3.2.8 on 2022-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0005_auto_20220601_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideruseradditionaldata',
            name='about',
            field=models.TextField(default=None, null=True),
        ),
    ]
