# Generated by Django 3.2.8 on 2022-06-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0007_user_admin_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=None, null=True),
        ),
    ]
