# Generated by Django 3.2.8 on 2022-06-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0008_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
