# Generated by Django 3.2.8 on 2022-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0009_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countryCode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
