# Generated by Django 3.2.8 on 2022-06-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0011_alter_user_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideruseradditionaldata',
            name='fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='PatientUserAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.IntegerField(default=0, null=True)),
                ('maxPrice', models.IntegerField(default=0, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='patientData', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_user_additional_data',
            },
        ),
    ]
