# Generated by Django 3.2.8 on 2022-06-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0012_auto_20220621_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
