# Generated by Django 3.2.8 on 2022-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0014_alter_patientuseradditionaldata_maxprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
