# Generated by Django 3.2.8 on 2022-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0015_alter_user_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripeCustomerId',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
