# Generated by Django 3.2.8 on 2022-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0016_user_stripecustomerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripeCustomerId',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
