# Generated by Django 3.2.8 on 2022-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0017_alter_user_stripecustomerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAccountConfigComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stripeProviderAccountId',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
