# Generated by Django 3.2 on 2022-08-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0019_providerstripeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideruseradditionaldata',
            name='licenseTypeId',
            field=models.ForeignKey(db_column='licenseTypeId', on_delete=django.db.models.deletion.CASCADE, related_name='licenseTypeIdDataa', to='auth_APIs.licensetype'),
        ),
    ]
