# Generated by Django 3.2 on 2022-08-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0021_auto_20220819_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideruseradditionaldata',
            name='fee',
            field=models.IntegerField(default=200, null=True),
        ),
    ]
