# Generated by Django 3.2 on 2022-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0022_alter_provideruseradditionaldata_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuseradditionaldata',
            name='maxPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientuseradditionaldata',
            name='minPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provideruseradditionaldata',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
