# Generated by Django 3.2 on 2022-08-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0023_auto_20220823_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideruseradditionaldata',
            name='licenseName',
        ),
        migrations.RemoveField(
            model_name='provideruseradditionaldata',
            name='licenseNumber',
        ),
        migrations.RemoveField(
            model_name='provideruseradditionaldata',
            name='licenseTypeId',
        ),
    ]
