# Generated by Django 3.2 on 2022-08-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0025_auto_20220824_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideruseradditionaldata',
            name='licenseName',
        ),
        migrations.RemoveField(
            model_name='provideruseradditionaldata',
            name='licenseNumber',
        ),
        migrations.RemoveField(
            model_name='provideruseradditionaldata',
            name='licenseTypeId',
        ),
    ]
