# Generated by Django 3.2 on 2022-08-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0027_alter_user_gendertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerstripeaccount',
            name='loginLink',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
