# Generated by Django 3.2 on 2022-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0028_providerstripeaccount_loginlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerstripeaccount',
            name='loginLink',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
