# Generated by Django 3.2 on 2022-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0029_alter_providerstripeaccount_loginlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuseradditionaldata',
            name='shareMedicalRecord',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
