# Generated by Django 3.2.8 on 2022-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcarddetail',
            name='fingerprint',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
