# Generated by Django 3.2.8 on 2022-07-22 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchAPIs', '0005_alter_requestassign_assignstatus'),
        ('paymentAPIs', '0002_savedcarddetail_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255)),
                ('paymentStatus', models.IntegerField(choices=[(1, 'initiated'), (2, 'success'), (3, 'pending'), (4, 'Falied'), (5, 'refunded'), (6, 'failed'), (7, 'cancelled')], default=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('consultantiontId', models.ForeignKey(db_column='consultantiontId', on_delete=django.db.models.deletion.CASCADE, related_name='consultantiont_trans_Id', to='searchAPIs.consultantion')),
                ('paymentMethodId', models.ForeignKey(db_column='paymentMethodId', on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_ref', to='paymentAPIs.savedcarddetail')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userId_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
