# Generated by Django 3.2.8 on 2022-07-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPIs', '0004_auto_20220722_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='callDuration',
            field=models.IntegerField(default=None),
        ),
    ]
