# Generated by Django 3.2.8 on 2022-07-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPIs', '0005_alter_transaction_callduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciept',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
