# Generated by Django 3.2 on 2022-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPIs', '0006_transaction_reciept'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='netAmmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripeFee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True),
        ),
    ]
