# Generated by Django 3.2 on 2022-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPIs', '0007_auto_20220830_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='adminCharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True),
        ),
    ]
