# Generated by Django 3.2 on 2022-09-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPIs', '0008_transaction_admincharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paymentMethodId',
            field=models.ForeignKey(db_column='paymentMethodId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_ref', to='paymentAPIs.savedcarddetail'),
        ),
    ]
