# Generated by Django 3.2 on 2022-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPriceAndFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(blank=True, default=0)),
                ('minPrice', models.IntegerField(blank=True, default=0)),
                ('maxPrice', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
