# Generated by Django 3.2.8 on 2022-06-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignStatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'X')], default=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('providerId', models.ForeignKey(db_column='providerId', on_delete=django.db.models.deletion.CASCADE, related_name='provider_assign_id', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userId_request_assign', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests_assign',
            },
        ),
    ]
