# Generated by Django 3.2.8 on 2022-06-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchAPIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestassign',
            name='userId',
        ),
        migrations.CreateModel(
            name='Consultantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMode', models.IntegerField(choices=[(1, 'online'), (2, 'cash')], null=True)),
                ('paymentStatus', models.IntegerField(choices=[(1, 'pending'), (2, 'payment_recieved'), (3, 'payment_cancelled'), (4, 'refunded')], null=True)),
                ('consultantionStatus', models.IntegerField(choices=[(1, 'pending'), (2, 'accepted'), (3, 'rejected'), (4, 'completed'), (5, 'failed')])),
                ('consultantiontFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doctorRating', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=255, null=True)),
                ('providerId', models.ForeignKey(db_column='providerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultantion_doctorId', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='consultantion_userId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultantions',
            },
        ),
        migrations.AddField(
            model_name='requestassign',
            name='consultantiontId',
            field=models.ForeignKey(db_column='consultantiontId', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultantiont_assign_Id', to='searchAPIs.consultantion'),
            preserve_default=False,
        ),
    ]
