# Generated by Django 3.2.8 on 2022-07-19 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchAPIs', '0003_auto_20220629_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentGoal', models.CharField(max_length=450)),
                ('subjective', models.CharField(max_length=450)),
                ('objective', models.CharField(max_length=450)),
                ('assessment', models.CharField(max_length=450)),
                ('plan', models.CharField(max_length=450)),
                ('signatureUrl', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('consultantiontId', models.ForeignKey(db_column='consultantiontId', on_delete=django.db.models.deletion.CASCADE, related_name='consultantiont_for_note', to='searchAPIs.consultantion')),
            ],
            options={
                'db_table': 'provider_progress_notes',
            },
        ),
    ]
