# Generated by Django 3.2 on 2022-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchAPIs', '0005_alter_requestassign_assignstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantion',
            name='callDuration',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
